// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigAndWarnings() {
  return window['go']['main']['App']['GetConfigAndWarnings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function LaunchItem(arg1, arg2) {
  return window['go']['main']['App']['LaunchItem'](arg1, arg2);
}

export function ListConfigFiles() {
  return window['go']['main']['App']['ListConfigFiles']();
}

export function SearchItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchItems'](arg1, arg2, arg3);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}
