// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LaunchItem(arg1:Record<string, any>,arg2:Array<string>):Promise<void>;

export function SearchItems(arg1:string,arg2:string,arg3:string):Promise<Array<main.Item>>;
